http:
  routers:
    ddns-updater-rtr:
      rule: "Host(`ddnsupdater.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: ddns-updater-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    ddns-updater-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:8000" # http://IP-ADDRESS:PORT