http:
  routers:
    cwa-downloader-rtr:
      rule: "Host(`cwadownloader.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: cwa-downloader-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    cwa-downloader-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:8097" # http://IP-ADDRESS:PORT