http:
  routers:
    shellinabox-rtr:
      rule: "Host(`shell.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: shellinabox-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    shellinabox-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:4200" # http://IP-ADDRESS:PORT