http:
  routers:
    paperless-ngx-rtr:
      rule: "Host(`paperless.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: paperless-ngx-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    paperless-ngx-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:8001" # http://IP-ADDRESS:PORT