http:
  routers:
    readarr-rtr:
      rule: "Host(`readarr.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: readarr-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    readarr-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:8787" # http://IP-ADDRESS:PORT