http:
  routers:
    radarr-rtr:
      rule: "Host(`radarr.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: radarr-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    radarr-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:7878" # http://IP-ADDRESS:PORT