http:
  routers:
    huntarr-rtr:
      rule: "Host(`huntarr.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: huntarr-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    huntarr-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:9705" # http://IP-ADDRESS:PORT