http:
  routers:
    adminer-rtr:
      rule: "Host(`adminer.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: adminer-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    adminer-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:8084" # http://IP-ADDRESS:PORT