http:
  routers:
    plex-rtr:
      rule: "Host(`plex.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: plex-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    plex-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:32400" # http://IP-ADDRESS:PORT