http:
  routers:
    glances-rtr:
      rule: "Host(`glances.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: glances-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    glances-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:61208" # http://IP-ADDRESS:PORT