http:
  routers:
    dozzle-rtr:
      rule: "Host(`dozzle.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia
      service: dozzle-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    dozzle-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111:8082" # http://IP-ADDRESS:PORT