services:
  # Gluetun - VPN Client for Docker Containers and More
  # Gluetun only for use by torrent clients + on demand lan devices.
  # Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
      - t3_proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

    ports:
      # Transmission Web UI
      - "$TRANSMISSION_PORT:9091"
      # Transmission peer port
      - "51413:51413/tcp"
      - "51413:51413/udp"

    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun

    environment:
      TZ: $TZ
      VPN_SERVICE_PROVIDER: $GLUETUN_VPN_SERVICE_PROVIDER
      VPN_TYPE: $GLUETUN_VPN_TYPE
      WIREGUARD_PRIVATE_KEY: $GLUETUN_WIREGUARD_PRIVATE_KEY
      WIREGUARD_ADDRESSES: $GLUETUN_WIREGUARD_ADDRESSES

    # Healthcheck used by Transmission depends_on: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "https://ipinfo.io/ip"]
      interval: 30s
      timeout: 10s
      retries: 5