services:
  # Lidarr - Music Management
  lidarr:
    # image: lscr.io/linuxserver/lidarr:latest
    image: blampe/lidarr:latest
    container_name: lidarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "starr", "all"]
    networks:
      - default
      # - t3_proxy
    ports:
      - "$LIDARR_PORT:8686"
    volumes:
      - $DOCKERDIR/appdata/lidarr:/config
      - $MEDIADIR1:/data/media
      # - $MEDIADIR2:/data/media2
      # - $MEDIADIR3:/data/media3
      - $DOWNLOADSDIR:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
