services:
  # Replace or pass in APPDATA (below).
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    networks:
      - default
      - t3_proxy
    ports:
      - "5454:5454"
    volumes:
      - $DOCKERDIR/appdata/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      DN_API_KEY: $DN_API_KEY
      DN_AUTO_UPDATE: off