services:
  # Readarr - eBooks Management
  readarr:
    image: lscr.io/linuxserver/readarr:develop-version-0.4.18.2805
    container_name: readarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "starr", "all"]
    networks:
      - default
      # - t3_proxy
    ports:
      - "$READARR_PORT:8787"
    volumes:
      - $DOCKERDIR/appdata/readarr:/config
      - $BOOKSDIR:/data
      - $DOWNLOADSDIR:/data 
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER